### ISSUE TITLE
Permissions for Repo Prevent Assigning Labels

### ISSUE THREAD

**Issue by pcodes** [gwu-iot/collaboration#32]
@gparmer I noticed for your paper issue you include a label for "paper-discussion", and you assigned yourself the issue. In the instructions, it does mention that we should use the `paper discussion` label, but due to the repo permissions we are unable to do so. If this is actually something we should do, could you update the permissions?

**Comment by gparmer** [comment]
Hmmm, that's annoying. As I don't want to spend a bunch of time setting the permissions on the org and going back and forth with one of you for tests, I'm going to keep it simple and add the labels myself. If there is another reason to add perms, I will.
